# Generated by Django 5.1.7 on 2025-05-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='default_username', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
