# Generated by Django 5.1.7 on 2025-10-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_dealer',
            field=models.BooleanField(default=False),
        ),
    ]
