# Generated by Django 5.1.7 on 2025-04-07 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_articletag_alter_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.DeleteModel(
            name='ArticleTag',
        ),
    ]
