# Generated by Django 5.1.7 on 2025-04-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_category_slug_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
