# Generated by Django 5.1.7 on 2025-05-22 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_hashtag_slug'),
        ('manufacturers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='carmodelyear',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='carspecification',
            name='year',
        ),
        migrations.AddField(
            model_name='blog',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='manufacturers.manufacturer'),
        ),
        migrations.DeleteModel(
            name='CarBrand',
        ),
        migrations.DeleteModel(
            name='CarModel',
        ),
        migrations.DeleteModel(
            name='CarModelYear',
        ),
        migrations.DeleteModel(
            name='CarSpecification',
        ),
    ]
