# Generated by Django 5.1.7 on 2025-12-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past due'), ('cancelled', 'Cancelled'), ('unpaid', 'Unpaid'), ('expired', 'Expired')], default='trialing', max_length=32),
        ),
    ]
