# Generated by Django 5.1.7 on 2025-04-09 18:01

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0002_userreviewfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('cover_image', models.ImageField(upload_to='guide_covers/')),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('excerpt', models.TextField(blank=True, max_length=400)),
                ('guide_type', models.CharField(choices=[('BUYING', 'Buying Guide'), ('SELLING', 'Selling Guide')], max_length=10)),
                ('estimated_read_time', models.PositiveIntegerField(help_text='Estimated read time in minutes')),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('difficulty_level', models.CharField(blank=True, choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('EXPERT', 'Expert')], max_length=20, null=True)),
                ('call_to_action_text', models.CharField(blank=True, max_length=100)),
                ('call_to_action_url', models.URLField(blank=True)),
                ('seo_title', models.CharField(blank=True, max_length=150)),
                ('seo_description', models.TextField(blank=True, max_length=300)),
                ('thumbnail_alt_text', models.CharField(blank=True, max_length=150)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guides', to=settings.AUTH_USER_MODEL)),
                ('related_brands', models.ManyToManyField(blank=True, related_name='guides', to='reviews.carbrand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guides', to='guides.guidecategory')),
                ('hashtags', models.ManyToManyField(blank=True, to='guides.hashtag')),
            ],
            options={
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
    ]
