# Generated by Django 5.1.7 on 2025-04-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='related_brands',
        ),
    ]
