# Generated by Django 5.1.7 on 2025-10-29 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_listings', '0016_alter_carlisting_options_and_more'),
        ('dealers', '0006_dealer_cars_listed_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerDailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_listings', models.PositiveIntegerField(default=0)),
                ('new_listings', models.PositiveIntegerField(default=0)),
                ('sold_listings', models.PositiveIntegerField(default=0)),
                ('active_listings', models.PositiveIntegerField(default=0)),
                ('avg_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('median_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('avg_age_days', models.FloatField(default=0.0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('leads', models.PositiveIntegerField(default=0)),
                ('sell_through_rate', models.FloatField(default=0.0, help_text='sold_listings / active_listings')),
                ('health_score', models.FloatField(default=0.0, help_text='Composite performance metric combining sales velocity, engagement, and price realism.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='dealers.dealer')),
            ],
            options={
                'verbose_name': 'Dealer Daily Metric',
                'verbose_name_plural': 'Dealer Daily Metrics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['dealer', 'date'], name='dealer_dash_dealer__96cefa_idx'), models.Index(fields=['date'], name='dealer_dash_date_0156c8_idx')],
                'unique_together': {('dealer', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ListingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('view', 'View'), ('lead', 'Lead'), ('sold', 'Sold'), ('deleted', 'Deleted')], max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_events', to='dealers.dealer')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_events', to='car_listings.carlisting')),
            ],
            options={
                'verbose_name': 'Listing Event',
                'verbose_name_plural': 'Listing Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dealer', 'event_type', 'created_at'], name='dealer_dash_dealer__6f916c_idx'), models.Index(fields=['created_at'], name='dealer_dash_created_440be0_idx')],
            },
        ),
    ]
