// components/ExploreCars/carData.js

export const carTypes = [
    { name: "Sedan", iconClass: "fi fi-rr-car-side" },
    { name: "SUV", iconClass: "fi fi-rr-car" },
    { name: "Convertible", iconClass: "fi fi-rr-car-roof" },
    { name: "Coupe", iconClass: "fi fi-rr-car-alt" },
    { name: "Hatchback", iconClass: "fi fi-rr-car-hatchback" }, // or fallback
    { name: "Wagon", iconClass: "fi fi-rr-wagon" }, // May need fallback
    { name: "Pickup", iconClass: "fi fi-rr-pickup" },
    { name: "Minivan", iconClass: "fi fi-rr-van" }
  ];
  
  export const mainManufacturersData = [
    { name: "Abarth", logoSrc: "/Brand_logos/abt.png" },
    { name: "Acura", logoSrc: "/Brand_logos/acura.png" },
    { name: "Alfa Romeo", logoSrc: "/Brand_logos/alpharomeo.png" },
    { name: "Aston Martin", logoSrc: "/Brand_logos/aston-martin.png" },
    { name: "Audi", logoSrc: "/Brand_logos/audi.png" },
    { name: "Bentley", logoSrc: "/Brand_logos/bentley.png" },
    { name: "BYD", logoSrc: "/Brand_logos/byd.png" },
    { name: "Cadillac", logoSrc: "/Brand_logos/cadillac.png" },
    { name: "Chevrolet", logoSrc: "/Brand_logos/chevrolet.png" },
    { name: "Chrysler", logoSrc: "/Brand_logos/chrylser.png" },
    { name: "Citroen", logoSrc: "/Brand_logos/citroen.png" },
    { name: "Cupra", logoSrc: "/Brand_logos/cupra.png" },
    { name: "Dacia", logoSrc: "/Brand_logos/dacia.png" },
    { name: "Daihatsu", logoSrc: "/Brand_logos/daihatsu.png" },
    { name: "Dodge", logoSrc: "/Brand_logos/dodge.png" },
    { name: "DS", logoSrc: "/Brand_logos/ds.png" },
    { name: "Ferrari", logoSrc: "/Brand_logos/ferrari.png" },
    { name: "Fiat", logoSrc: "/Brand_logos/fiat.png" },
    { name: "Ford", logoSrc: "/Brand_logos/ford.png" },
    { name: "Genesis", logoSrc: "/Brand_logos/genesis.png" },
    { name: "GMC", logoSrc: "/Brand_logos/gmc.png" },
    { name: "GWM Ora", logoSrc: "/Brand_logos/gwm-ora.png" },
    { name: "Hino", logoSrc: "/Brand_logos/hino.png" },
    { name: "Honda", logoSrc: "/Brand_logos/honda.png" },
    { name: "Hummer", logoSrc: "/Brand_logos/hummer.png" },
    { name: "Hyundai", logoSrc: "/Brand_logos/hyundai.png" },
    { name: "INEOS", logoSrc: "/Brand_logos/ineos.png" },
    { name: "Infiniti", logoSrc: "/Brand_logos/infiniti.png" },
    { name: "Isuzu", logoSrc: "/Brand_logos/isuzu.png" },
    { name: "Jaecoo", logoSrc: "/Brand_logos/jaecoo.png" },
    { name: "Jaguar", logoSrc: "/Brand_logos/jaguar.png" },
    { name: "Jeep", logoSrc: "/Brand_logos/jeep.png" },
    { name: "Kia", logoSrc: "/Brand_logos/kia.png" },
    { name: "Lada", logoSrc: "/Brand_logos/lada.png" },
    { name: "Land Rover", logoSrc: "/Brand_logos/land-rover.png" },
    { name: "Lexus", logoSrc: "/Brand_logos/Lexus.png" },
    { name: "Lincoln", logoSrc: "/Brand_logos/lincoln.png" },
    { name: "Lotus", logoSrc: "/Brand_logos/lotus.png" },
    { name: "Lucid", logoSrc: "/Brand_logos/lucid.png" },
    { name: "Maserati", logoSrc: "/Brand_logos/maserati.png" },
    { name: "Mazda", logoSrc: "/Brand_logos/mazda.png" },
    { name: "MG", logoSrc: "/Brand_logos/mg.png" },
    { name: "MINI", logoSrc: "/Brand_logos/mini.png" },
    { name: "Mitsubishi", logoSrc: "/Brand_logos/mitsubishi.png" },
    { name: "Nissan", logoSrc: "/Brand_logos/nissan.png" },
    { name: "OMODA", logoSrc: "/Brand_logos/omoda.png" },
    { name: "Opel", logoSrc: "/Brand_logos/opel.png" },
    { name: "Peugeot", logoSrc: "/Brand_logos/peugeot.png" },
    { name: "Polestar", logoSrc: "/Brand_logos/polestar.png" },
    { name: "Pontiac", logoSrc: "/Brand_logos/pontiac.png" },
    { name: "Renault", logoSrc: "/Brand_logos/renault.png" },
    { name: "Rolls-Royce", logoSrc: "/Brand_logos/rollsroyce.jpg" },
    { name: "Saturn", logoSrc: "/Brand_logos/saturn.png" },
    { name: "Scania", logoSrc: "/Brand_logos/scania.png" },
    { name: "SEAT", logoSrc: "/Brand_logos/seat.png" },
    { name: "Skoda", logoSrc: "/Brand_logos/skoda.png" },
    { name: "Smart", logoSrc: "/Brand_logos/smart.png" },
    { name: "SsangYong", logoSrc: "/Brand_logos/ssangyong.png" },
    { name: "Sterling", logoSrc: "/Brand_logos/sterling.png" },
    { name: "Subaru", logoSrc: "/Brand_logos/subaru.png" },
    { name: "Suzuki", logoSrc: "/Brand_logos/suzuki.png" },
    { name: "Tata", logoSrc: "/Brand_logos/tata.png" },
    { name: "Tesla", logoSrc: "/Brand_logos/tesla.png" },
    { name: "Toyota", logoSrc: "/Brand_logos/toyota.png" },
    { name: "Toyota Crown", logoSrc: "/Brand_logos/toyota-crown.png" },
    { name: "Vauxhall", logoSrc: "/Brand_logos/vauxhall.png" },
    { name: "Volkswagen", logoSrc: "/Brand_logos/volkswagen.png" },
    { name: "Volvo", logoSrc: "/Brand_logos/volvo.png" },
  ];
  
  export const subBrandsTuningData = [
    { name: "Alpina", logoSrc: "/Brand_logos/alpina.png" },
    { name: "BMW M", logoSrc: "/Brand_logos/bmw-m.png" },
    { name: "Brabus", logoSrc: "/Brand_logos/brabus.png" },
    { name: "Koenigsegg", logoSrc: "/Brand_logos/koenigsegg.png" },
    { name: "Lamborghini", logoSrc: "/Brand_logos/lamborghini.svg" },
    { name: "Mansory", logoSrc: "/Brand_logos/mansory.png" },
    { name: "McLaren", logoSrc: "/Brand_logos/mclaren.png" },
    { name: "Mercedes-AMG", logoSrc: "/Brand_logos/mercedes-amg.png" },
    { name: "Nissan Nismo", logoSrc: "/Brand_logos/nissan-nismo.png" },
    { name: "Pagani", logoSrc: "/Brand_logos/pagani.png" },
    { name: "Porsche", logoSrc: "/Brand_logos/porsche.png" },
    { name: "Rimac", logoSrc: "/Brand_logos/rimac.png" },
    { name: "Saleen", logoSrc: "/Brand_logos/saleen.png" },
    { name: "Abarth", logoSrc: "/Brand_logos/abt.png" }, // Appears as both main and tuning brand
  ];  