# Generated by Django 5.1.7 on 2025-05-22 10:31

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0001_initial'),
        ('reviews', '0002_userreviewfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='manufacturers.manufacturer'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
