# Generated by Django 5.1.7 on 2025-05-22 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0002_manufacturer_image'),
        ('reviews', '0003_car_manufacturer_alter_review_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='brand',
        ),
        migrations.AddField(
            model_name='review',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='manufacturers.manufacturer'),
        ),
        migrations.DeleteModel(
            name='CarBrand',
        ),
    ]
