# Generated by Django 5.1.7 on 2025-06-11 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_remove_car_brand_review_manufacturer_delete_carbrand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reviewcomment',
            name='review',
        ),
        migrations.RemoveField(
            model_name='reviewsection',
            name='review',
        ),
        migrations.RemoveField(
            model_name='userreviewfeedback',
            name='review',
        ),
        migrations.RemoveField(
            model_name='userreviewfeedback',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='review',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='ReviewComment',
        ),
        migrations.DeleteModel(
            name='ReviewSection',
        ),
        migrations.DeleteModel(
            name='UserReviewFeedback',
        ),
    ]
