# Generated by Django 5.1.7 on 2025-04-05 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='years_in_business',
        ),
    ]
