# Generated by Django 5.1.7 on 2025-10-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0003_remove_dealer_email_remove_dealer_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealerrating',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='dealer',
            name='business_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
