# Generated by Django 5.1.7 on 2025-10-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0004_alter_dealerrating_options_dealer_business_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
