# Generated by Django 5.1.7 on 2025-10-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0005_alter_dealer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='cars_listed_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
