# Generated by Django 5.1.7 on 2025-10-30 09:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0006_dealer_cars_listed_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dealer', 'verbose_name_plural': 'Dealers'},
        ),
        migrations.AlterModelOptions(
            name='dealerrating',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dealer Rating', 'verbose_name_plural': 'Dealer Ratings'},
        ),
        migrations.AlterField(
            model_name='dealer',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='cars_listed_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='cars_sold_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='user',
            field=models.OneToOneField(help_text='The user account associated with this dealer.', on_delete=django.db.models.deletion.CASCADE, related_name='dealer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dealerrating',
            name='dealer',
            field=models.ForeignKey(help_text='The dealer being reviewed.', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='dealers.dealer'),
        ),
        migrations.AlterField(
            model_name='dealerrating',
            name='rating',
            field=models.IntegerField(help_text='Rating value between 1 and 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='dealerrating',
            name='user',
            field=models.ForeignKey(help_text='The user who provided the rating.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
