# Generated by Django 5.1.7 on 2025-11-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0008_dealer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated slug for dealer URLs.', max_length=255, unique=True),
        ),
    ]
