# Generated by Django 5.1.7 on 2025-05-22 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0001_initial'),
        ('news_articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='brand',
        ),
        migrations.AddField(
            model_name='newsitem',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_items', to='manufacturers.manufacturer'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
