# Generated by Django 5.1.7 on 2025-04-05 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listings', '0003_alter_car_main_image_alter_carimage_image'),
        ('dealers', '0003_remove_dealer_email_remove_dealer_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='dealers.dealer'),
        ),
        migrations.AlterField(
            model_name='car',
            name='body_style',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback'), ('Convertible', 'Convertible'), ('SUV', 'SUV'), ('Crossover', 'Crossover'), ('Pickup Truck', 'Pickup Truck'), ('Van', 'Van'), ('Wagon', 'Wagon')], max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric')], max_length=50),
        ),
    ]
