# Generated by Django 5.1.7 on 2025-04-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listings', '0004_car_dealer_alter_car_body_style_alter_car_fuel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='has_warranty',
            field=models.BooleanField(default=False),
        ),
    ]
