# Generated by Django 5.1.7 on 2025-04-05 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listings', '0005_car_has_warranty'),
        ('dealers', '0003_remove_dealer_email_remove_dealer_phone_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carimage',
            name='car',
        ),
        migrations.CreateModel(
            name='CarListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mileage', models.PositiveIntegerField()),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('CVT', 'CVT'), ('Dual-Clutch', 'Dual-Clutch'), ('Semi-Automatic', 'Semi-Automatic'), ('Other', 'Other')], max_length=20)),
                ('drivetrain', models.CharField(choices=[('FWD', 'Front-Wheel Drive'), ('RWD', 'Rear-Wheel Drive'), ('AWD', 'All-Wheel Drive'), ('4WD', 'Four-Wheel Drive')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric')], max_length=20)),
                ('body_style', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('Truck', 'Truck'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Wagon', 'Wagon'), ('Other', 'Other')], max_length=20)),
                ('exterior_color', models.CharField(blank=True, max_length=50, null=True)),
                ('interior_color', models.CharField(blank=True, max_length=50, null=True)),
                ('vin', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('engine', models.CharField(blank=True, max_length=100, null=True)),
                ('title_status', models.CharField(blank=True, choices=[('Clean', 'Clean'), ('Salvage', 'Salvage'), ('Rebuilt', 'Rebuilt'), ('Parts Only', 'Parts Only')], max_length=50, null=True)),
                ('seller_type', models.CharField(choices=[('Dealer', 'Dealer'), ('Private Seller', 'Private Seller')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_sold', models.BooleanField(default=False)),
                ('has_warranty', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_listings', to='dealers.dealer')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarListingEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('car_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='car_listings.carlisting')),
            ],
        ),
        migrations.CreateModel(
            name='CarListingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('car_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='car_listings.carlisting')),
            ],
        ),
        migrations.CreateModel(
            name='CarListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_listing_images/')),
                ('car_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='car_listings.carlisting')),
            ],
        ),
        migrations.CreateModel(
            name='CarListingKnownFlaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('car_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_flaws', to='car_listings.carlisting')),
            ],
        ),
        migrations.CreateModel(
            name='CarListingModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('car_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='car_listings.carlisting')),
            ],
        ),
        migrations.CreateModel(
            name='CarListingVideoWalkaround',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('car_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='car_listings.carlisting')),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='CarImage',
        ),
    ]
