# Generated by Django 5.1.7 on 2025-05-22 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listings', '0006_remove_carimage_car_carlisting_carlistingequipment_and_more'),
        ('manufacturers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlisting',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_listings', to='manufacturers.manufacturer'),
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='make',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
