# Generated by Django 5.1.7 on 2025-05-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listings', '0007_carlisting_manufacturer_alter_carlisting_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlisting',
            name='make',
            field=models.CharField(max_length=100),
        ),
    ]
