# Generated by Django 5.1.7 on 2025-05-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listings', '0008_alter_carlisting_make'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlisting',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used')], default='used', max_length=10),
        ),
    ]
