# Generated by Django 5.1.7 on 2025-10-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listings', '0009_carlisting_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlisting',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used')], default='Used', max_length=10),
        ),
    ]
