# Generated by Django 5.1.7 on 2025-10-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listings', '0011_auto_20251007_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlisting',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
