# Generated by Django 5.1.7 on 2025-10-28 10:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listings', '0014_alter_carlisting_slug'),
        ('manufacturers', '0003_manufacturer_achievements_manufacturer_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlistingimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_listings', to='manufacturers.manufacturer'),
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
