# Generated by Django 5.1.7 on 2025-10-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listings', '0015_carlistingimage_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carlisting',
            options={'ordering': ['-created_at'], 'verbose_name': 'Car Listing', 'verbose_name_plural': 'Car Listings'},
        ),
        migrations.AlterModelOptions(
            name='carlistingimage',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='mileage',
            field=models.PositiveIntegerField(help_text='Mileage in kilometers'),
        ),
    ]
