# Generated by Django 5.1.7 on 2025-10-30 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listings', '0016_alter_carlisting_options_and_more'),
        ('dealers', '0007_alter_dealer_options_alter_dealerrating_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlisting',
            name='dealer',
            field=models.ForeignKey(blank=True, help_text='Dealer associated with this listing (if seller is a dealer).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_listings', to='dealers.dealer'),
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='seller',
            field=models.ForeignKey(help_text='User who created the car listing.', on_delete=django.db.models.deletion.CASCADE, related_name='car_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
