# Generated by Django 5.1.7 on 2025-05-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0002_manufacturer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='achievements',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
